package com.example.CRUDApplication.entity.libraryEntity;

public enum BookCategory {

    PROGRAMMING,
    DATABASE,
    NETWORKING,
    CYBER_SECURITY,
    ARTIFICIAL_INTELLIGENCE,
    MACHINE_LEARNING,
    CLOUD_COMPUTING,
    DATA_SCIENCE,
    SOFTWARE_ENGINEERING,
    OPERATING_SYSTEM,
    COMPUTER_ARCHITECTURE,
    ELECTRONICS,
    ELECTRICAL,
    MECHANICAL,
    CIVIL,
    MATHEMATICS,
    PHYSICS,
    CHEMISTRY,
    BIOLOGY,
    COMMERCE,
    ECONOMICS,
    MANAGEMENT,
    ACCOUNTING,
    HISTORY,
    GEOGRAPHY,
    POLITICAL_SCIENCE,
    ENGLISH,
    LITERATURE,
    GENERAL_KNOWLEDGE,
    FICTION,
    NON_FICTION

}
